### ISSUE TITLE
Dólar Mep a "precio asegurado" y a "precio estimado" andan mal, AYUDA

### ISSUE THREAD

**Issue by salen11934** [nacho-herrera/pyCocos#12]
1) Hola, intento obtener el dolar mep a precio asegurado y no me da el valor que veo en la app de cocos. Este valor lo trato de obtener con la siguiente función:

mep = app.get_dolar_mep_info()

![dolar mep asegurado](https://github.com/nacho-herrera/pyCocos/assets/165956917/b6fb5632-bc24-4742-9da0-2e87b2fa74ec)
![dolar mep asegurado en app de cocos](https://github.com/nacho-herrera/pyCocos/assets/165956917/f161fd13-28e0-4a80-9236-69a5e460de11)

2)
A la hora de obtener el precio del mep "NO asegurado", me devuelve el siguiente error:

Función:
open_mep = app.get_open_dolar_mep_info() 

Respuesta:
![error al obtener dolar mep abierto](https://github.com/nacho-herrera/pyCocos/assets/165956917/25f89b7c-b6b0-49bf-9c2e-1a1b4e93548e)

AYUDA!

**Comment by nacho-herrera** [comment]
Hola, ahora lo reviso. Cocos tiene dos precios de MEP, ese metodo traia la otra cotizacion, que era la que estaba vigente al momento de hacer la biblioteca. Nunca opere MEP por cocos por lo que no pude capturar los metodos necesarios para hacer la operacion.

**Comment by salen11934** [comment]
Hola, gracias por la respuesta! Actualmente cocos brindo dos valores de mep. Durante las 24 horas tenés la posibilidad de operar mep a precio asegurado. Desde las 11.15 hasta las 16.00 te ofrece un mep a precio asegurado y un mep a precio estimado (figuran al mismo tiempo las dos cotizaciones y con un botos elegís una u otra). Te dejo unas imágenes de la app:
![image](https://github.com/nacho-herrera/pyCocos/assets/165956917/6ee048ee-1431-4214-a982-d96528dfa3ae) (fuera de las 11.15 - 16.00 solo figura la cotización de precio asegurado).

**Comment by salen11934** [comment]
Espero puedas agregar la cotización de precio asegurado! Gracias!

**Comment by nacho-herrera** [comment]
Ahi pude agregarlo. Me faltarian ver de hacer los metodos para enviar las solicitudes pero actualmente no tengo saldo como para ver que requests hace. Avisame si es algo que te interesaria hacer (mandar instrucciones de compra/venta desde la biblioteca) e intento capturar esos metodos. 
el request app.get_dolar_mep_info() te va a traer un diccionario con 3 keys, open se refiere al precio estimado, close se refiere al precio asegurado y overnight al precio que podes operar con la rueda cerrada. En este momento overnight y close tienen los mismos valores pero entiendo que una vez cierre la rueda van a ser diferentes.

**Comment by salen11934** [comment]
Genial! muchas gracias por la implementación. Actualmente estoy estudiando unas estrategias que utilizan el mep a precio asegurado. Cómo aún no las puse en producción no llegué a la etapa de operar, pero si necesitaría poder comprar y vender mep a precio asegurado desde la biblioteca. Si se puede agregar sería un golazo! Gracias!
