### ISSUE TITLE
Cómo obtener las cotizaciones de los bonos?

### ISSUE THREAD

**Issue by salen11934** [nacho-herrera/pyCocos#13]
Hola, estoy tratando de obtener la cotización de los bonos con la siguiente sentencia. Pero me devuelve error! Ayuda!

BonosPublicos_BonosSoberanosUSD_ARS_CI = app.get_instrument_list_snapshot(instrument_type=app.instrument_types.BONOS, instrument_subtype=app.instrument_subtypes.USD, settlement=app.settlements.T0, currency=app.currencies.USD, segment=app.segments.DEFAULT)

![image](https://github.com/nacho-herrera/pyCocos/assets/165956917/e198218c-1877-4f11-9cbc-4f685e83ba52)
![image](https://github.com/nacho-herrera/pyCocos/assets/165956917/3d4c9efe-a8f9-4ae6-a3a4-77b847b7bde9)

**Comment by lisandro** [comment]
Hola @salen11934, probé el mismo método que mencionas y me funciona bien? Que version de la biblioteca tenes? Otros métodos te funcionan bien?

**Comment by salen11934** [comment]
Hola, gracias por la respuesta. Si, ahora me funciona bien. Era un problema de versión de biblioteca. Gracias!

**Comment by nacho-herrera** [comment]
Genial! gracias por confirmar.
