### ISSUE TITLE
Autentificación

### ISSUE THREAD

**Issue by salen11934** [nacho-herrera/pyCocos#14]
Hola, durante las últimas semanas venía usando la biblioteca sin inconvenientes. Hoy no me anduvo, y es porque en cocos implementaron la autentificación con google authentificator. Se podrá sortear ese obstáculo para seguir usando la biblioteca? Espero puedan ayudarme! Saludos!

**Comment by salen11934** [comment]
![image](https://github.com/nacho-herrera/pyCocos/assets/165956917/fc2dc694-feef-449b-9177-f44cef6b7d81)

**Comment by nacho-herrera** [comment]
Buenas, si ayer agregue la validacion para google authenticator, la version 0.2.5 ya lo incluye. 
Funciona de dos formas posibles; podes ingresar el codigo manualmente (tanto sea de authenticator, mail o sms) al momento de inicializar la biblioteca (lo pide con un input) una vez ejecutada la inicializacion o podes proveer el TOPT Secret Key como parametro en la inicializacion y la biblioteca PyOTP genera el codigo automaticamente. 

Si en tu cuenta ya tenes Google Authenticator activado, tenes que usar el siguiente metodo para obtener la TOPT Secret Key 
Te dejo estas instrucciones que hizo @El_Raulo en telegram:
```
Sacar la topt_secret_key de Google Authenticator
================================================
En Google Authenticator ir a Transferir Cuentas - Exportar cuentas
Tildar solo Cocos, click en Siguiente y va a dar un QR
Usar el lector de qr del celu para escanearlo
Tratar de abrirlo, tiene que dar un link que arranca con: otpauth-migration : //offline?data=
Guardar ese link en un archivo C:\clave.txt

Ir a https://github.com/scito/extract_otp_secrets

git clone https://github.com/scito/extract_otp_secrets.git
cd extract_otp_secrets
pip install -U -r requirements.txt

python src/extract_otp_secrets.py C:\clave.txt

Tiene que devolver:
Name:    Cocos Crypto
Secret:  topt_secret_key_es_esta
Type:    totp

Listo!!!
```

Si aun no habilitaste Google Auth, antes de activarlo desde Configuracion > Seguridad en la app de cocos, hacele una captura de pantalla al QR y decodificalo con algun lector de codigos QR, la TOPT Secret Key es lo ultimo que aparece en ese URL 

`otpauth : //totp/app.cocos.capital:<your_email>?algorithm=SHA1&digits=6&issuer=app.cocos.capital&period=30&secret=<TOPT_Key>
`

Una vez que obtengas la TOPT Secret Key usando alguno de los dos metodos, tenes que inicializar la biblioteca de esta forma:
```
from pycocos import Cocos
app = Cocos(email="sample@email.com", password="S4mp13.p4ssW0rd", topt_secret_key="TOPT Secret Key")
```

**Comment by salen11934** [comment]
Genial, lo pruebo y te comento!. Muchas gracias!
