### ISSUE TITLE
No funciona el método get_instrument_list_snapshot

### ISSUE THREAD

**Issue by salen11934** [nacho-herrera/pyCocos#16]
Hola Nacho, dejó de funcionarme el método: get_instrument_list_snapshot. Lo venía usando pero con la última actualización del código dejó de funcionar.

te paso una imagen del error que me da:

![image](https://github.com/nacho-herrera/pyCocos/assets/165956917/fc367889-e041-4fee-8b06-1111c1287309)
![image](https://github.com/nacho-herrera/pyCocos/assets/165956917/d24407ca-3d4a-4be9-9b76-f2523694f7d6)

Podrás darme una mano con esto? Además, se podrá poner la opción para operar los dolares mep (asegurado y abierto) desde pycocos?

Desde ya, Gracias!

**Comment by nacho-herrera** [comment]
Buenas, lo reviso. Estos de cocos viven cambiando los metodos de la web y la biblioteca queda desactualizada.

Respecto a operar dolares desde pycocos, lo veo un poco mas complejo, cuando pueda hacer un par de operaciones manuales tomo nota de como son los metodos que usan y trato de agregarlos.

**Comment by nacho-herrera** [comment]
Buenas, actualiza a la version que acabo de publicar. 0.2.8, que deberia estar corregido el error que mencionas. 
`pip install --upgrade --force-reinstall pycocos`
