### ISSUE TITLE
El método logout() devuelve internal server error y no desconecta la app del broker.

### ISSUE THREAD

**Issue by cverri** [nacho-herrera/pyCocos#20]
El método logout() devuelve internal server error y no desconecta la app del broker. He intentado ver cual es el problema y no logro detectarlo. La respuesta es un 204, pero en el navegador aparece el error.

**Comment by nacho-herrera** [comment]
Gracias, creo que el problema es que agregaron un payload ahora al post, por lo que veo hay que agregar `{scope: global}`. Lo corrijo para la proxima version, hacen cambios practicamente todas las semanas
