### ISSUE TITLE
El método get_instrument_list_snapshot no devuelve datos

### ISSUE THREAD

**Issue by cverri** [nacho-herrera/pyCocos#21]
El método get_instrument_list_snapshot está devolviendo [ ].
Habrán cambiado algo del otro lago?

PD: Veo que los fines de semana no hay cotización en T2. Solo en T1. Eso era así antes?

**Comment by nacho-herrera** [comment]
Buenas, ya deberia andar, Cambiando el endpoint y sacaron ese metodo para devolver la lista "paginada". 

Respeto a lo de las cotizaciones, la verdad nunca lo probe.
