### ISSUE TITLE
Bad HTTP API Response. Error code: 403. Server response

### ISSUE THREAD

**Issue by marianos2024** [nacho-herrera/pyCocos#22]
Estimado Nacho, me da este error al hacer login: Bad HTTP API Response. Error code: 403. Server response y detalla todo el codigo HTML. Entiendo que cambiaron algo en los Headers y/o similar. Me podrias dar una mano. Abrazo!

**Comment by joacoarana** [comment]
Hola! A mi me sigue pasando!

**Comment by nacho-herrera** [comment]
Hola Joaco, como andas? Podes pasarme detalle del error que te sale? Tenes
la ultima version instalada?
