### ISSUE TITLE
Archivo incorrecto

### ISSUE THREAD

**Issue by Lucas-G-Lunix** [nacho-herrera/pyCocos#5]
Buenas!! 
Primero que nada gracias por la librería muy útil, estaba buscando algo así porque usaba Selenium para sacar la data de Cocos y no es lo mas ideal jajaja. 

Te abrí el issue porque se te escapo un PDF en el último push el que se llama **filename** te lo digo porque tiene información sensible.

**Comment by nacho-herrera** [comment]
Muchas gracias por avisar, ahi lo borre! 
Espero que ande bien la libreria, cualquier cosa me avisas y lo corrijo.
