### ISSUE TITLE
PyCocos dejó de funcionar.

### ISSUE THREAD

**Issue by cverri** [nacho-herrera/pyCocos#6]
El método appcocos.get_instrument_list_snapshot ha dejado de funcionar. Devuelve error 500. Probé de mil maneras hacerlo funcionar, sin exito. Cocos habrá cambiado los parámetros de la API? Otros métodos funcionan, este no devuelve las cotizaciones, solo Internal Server Error.

**Comment by nacho-herrera** [comment]
Buenas, gracias por avisar. Dieron de baja un endpoint ("api/v1/markets/types") con el que mostraban las posibles combinaciones de instrument type e instrument subtype que se usan para armar las listas de instrumentos y ahora lo tienen hardcodeado en el JS de la pagina. Tengo que modificarlo. Ni bien este andando de vuelta aviso por aca.

**Comment by cverri** [comment]
Espero que no sea una practica habitual de Cocos andar modificando los endpoints. Gracias por lo que hacés.

**Comment by joacoarana** [comment]
Sigue dando error?

**Comment by nacho-herrera** [comment]
Acabo de subir una version que corrije este error. Cualquier cosa me avisan!
