### ISSUE TITLE
Buy Power validation error

### ISSUE THREAD

**Issue by nacho-herrera** [nacho-herrera/pyCocos#7]
Hay un problema al validar el buy power si queres  comprar en CI.
Como valida el buy power antes de mandar la OC si querés comprar en CI no te deja:
La consulta app._validate_buy_power(long_ticker="AL30-0003-C-CT-ARS", quantity="1", price="2023") funciona OK.
Pero al hacer app._validate_buy_power(long_ticker="AL30-0001-C-CT-ARS", quantity="1", price="2023") da error.

**Comment by cverri** [comment]
Soy muy nuevo en Python, el cual dicen que es muy simple de entender, pero me está dando dolores de cabeza. Estoy desarrollando en... -si ya se, es obsoleto, pero a mi me funciona y con el 10% de la complejidad de Python- VFP10, 64 bits. (Me dedico a otra cosa. No soy programador, solo entusiasta). El servidor te devuelve un objeto jSon con los montos disponibles en CI, 24h y 48h. No tengo mi compu a mano, cuando pueda subo el payload que utilizo.


Actualizo: Directamente consultás a este endpoint: "api/v2/orders/buying-power" y te devuelve un objeto jSon con el dinero disponible en los distintos plazos.

**Comment by quique96** [comment]
Me parece que encontré un error que estaría relacionado:
cuando se ejecuta "app._find_instrument_code("AL30-0001-C-CT-ARS")" devuelve un '' . Esto sólo pasa con "AL30-0001-C-CT-ARS" y "AL30-0002-C-CT-ARS". En cambio con "AL30-0003-C-CT-ARS" devuelve  'AL30'. 

Luego, si en "app._get_price_factor" se reemplaza el output de esta función por 'AL30':
app._get_price_factor( instrument_code='AL30' , long_ticker="AL30-0001-C-CT-ARS", segment=app.segments.DEFAULT)
devuelve el factor de precio correcto '100'.

**Comment by nacho-herrera** [comment]
Ahi lo arregle, gracias muchachos!
